name: Node.js Unit Tests on Push and Pull Requests

on: [ push, pull_request ]
jobs:
  nodejs-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies with npm
        run: npm ci

      - name: Run unit tests with npm
        run: npm run test:unit
